FROM python:3.11.6-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /python-intern

WORKDIR /python-intern

COPY . /python-intern

RUN pip install --upgrade pip && pip install -r requirements_dev.txt

CMD ["pytest"]